### ISSUE TITLE
Does not work when we add "UINavigationController"

### ISSUE THREAD

**Issue by janczakb** [appssemble/appstore-card-transition#1]
Does not work when we add "UINavigationController"

**Comment by chelemen-razvan** [comment]
You are right. While it is fairly easy to adapt it to the `UINavigationController` model, the animation requires the master viewcontroller to be visible below the detail one while you interact with it (swipe down to dismiss). This is not possible with `UINavigationController` at least in a non-hacky  way as far as I know.

**Comment by janczakb** [comment]
Could you show an example of use?

**Comment by chelemen-razvan** [comment]
You'll have to implement this yourself since we are not planning to support this.

**Comment by komaldaudia-nv** [comment]
same issue I am facing, any quick help?
