### ISSUE TITLE
The picture has no smooth animation

### ISSUE THREAD

**Issue by janczakb** [appssemble/appstore-card-transition#2]
The picture has no smooth animation:

![ezgif-5-4b0fcf213757](https://user-images.githubusercontent.com/4959534/60379722-39cb9480-9a38-11e9-8773-7de494d04a44.gif)

**Comment by chelemen-razvan** [comment]
It is up to you to make sure the items in the cell and in the view controller have the same starting/ending position. Please check the readme. There are ways to do that, basically you must adjust the content offset of the scrollview using the provided callbacks, check the demo project also.
