### ISSUE TITLE
safeAreaInsets zero

### ISSUE THREAD

**Issue by fl034** [appssemble/appstore-card-transition#4]
In the CardDetailController safe area insets are always zero.
Tested on iOS 12 and 13.
Can this be configured somewhere?

**Comment by fl034** [comment]
Okay I figured that it's working correctly when I replace this `-1` with zero. Only that way the safe area insets are being passthrough correctly.

https://github.com/appssemble/appstore-card-transition/blob/4e98e9d0527ee4141b0bde282178d456beb9344c/AppstoreTransition/AppstoreTransition/PresentCardAnimator.swift#L132-L136

I couldn't notice the "super weird bug", but expected behaviour. If I set negative `aditionalSafeAreaInset` on the CardDetailController it works like I'd expect.

The library you got the base code from does this here

https://github.com/aunnnn/AppStoreiOS11InteractiveTransition/blob/4151879a5030a4f0c9fb28200ecc510f46722dc5/AppStoreInteractiveTransition/ViewControllers/CardDetailViewController.swift#L199-L205

So If you want you can test removing this workaround and add a helper method to reverse the top safeAreaInsets on the detail controller.

**Comment by chelemen-razvan** [comment]
You are right, I did not found any issue with 0 either but I thought I was missing something. Removed the -1 in https://github.com/appssemble/appstore-card-transition/commit/9aaa2ea30b7fa275e6f27c695ff29a4cded51aac
