### ISSUE TITLE
Can't use card transition within TabBarController 

### ISSUE THREAD

**Issue by ArdoThenardo** [appssemble/appstore-card-transition#6]
If a collection view controller is in TabBarController, the app will crashed when try to transition from collectionView to detail view.

<img width="739" alt="Screen Shot 2019-10-11 at 10 54 31" src="https://user-images.githubusercontent.com/50389533/66623485-16f37380-ec16-11e9-9b94-0eccea3a3fee.png">

But, if I don't use TabBarController, the app will work correctly when try to transition from collectionView to a detail view. 

Maybe I missed something or appstore-card-transition don't support TabBar for now?

**Comment by chelemen-razvan** [comment]
Fixed in https://github.com/appssemble/appstore-card-transition/commit/399705d0573a2485f0d8ad6ec2dc27cc0fe000d1

**Comment by tarastomchuk** [comment]
> Fixed in [399705d](https://github.com/appssemble/appstore-card-transition/commit/399705d0573a2485f0d8ad6ec2dc27cc0fe000d1)

Implemented your fix in live project - didn't work, same issue

![image](https://user-images.githubusercontent.com/35869411/74534735-13158c00-4f3d-11ea-9064-1b64584b21ac.png)
